databases:
  oracle:
    connection-string:
      jdbc-thin:
        template: "jdbc:oracle:thin:@//%s:%d/%s"
        port: 49125
      ldap:
        template: "ldap://%s:%d/%s,%s"
        servers: oid1puser.bankofamerica.com,oid2puser.bankofamerica.com,oid3puser.bankofamerica.com
        context: "cn=OracleContext,dc=bankofamerica,dc=com"
        port: 389
  h2:
    connection-string:
      jdbc-thin:
        template: "jdbc:h2:%s;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        port: 0

# Oracle Database Configuration
oracle:
  host: localhost
  port: 1521
  service: XE
  username: system
  password: oracle123
  
# Connection pool settings
  connection:
    pool:
      initial-size: 5
      max-size: 20
      min-idle: 5
      max-idle: 10
      timeout: 30000

# Logging configuration
logging:
  level:
    com.baml.mav.aieutil: DEBUG
    oracle: INFO