FROM container-registry.oracle.com/database/express:21.3.0

ENV ORACLE_PWD=oracle123
ENV ORACLE_CHARACTERSET=AL32UTF8

EXPOSE 1521
EXPOSE 5500

HEALTHCHECK --interval=30s --start-period=300s --timeout=10s --retries=3 \
  CMD sqlplus -L sys/oracle123@//localhost:1521/XE as sysdba <<< "exit" || exit 1 