version: '3.8'
services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    restart: unless-stopped
