-- Oracle Database Initialization Script
-- This script runs when the container starts for the first time

-- Create a test user for development
CREATE USER dev_user IDENTIFIED BY dev123;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO dev_user;
GRANT CREATE SESSION TO dev_user;
GRANT CREATE TABLE TO dev_user;
GRANT CREATE VIEW TO dev_user;
GRANT CREATE SEQUENCE TO dev_user;
GRANT CREATE PROCEDURE TO dev_user;

-- Create a test table
CREATE TABLE dev_user.test_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Insert some test data
INSERT INTO dev_user.test_table (name) VALUES ('Test Record 1');
INSERT INTO dev_user.test_table (name) VALUES ('Test Record 2');

COMMIT;

-- Set default tablespace
ALTER USER dev_user DEFAULT TABLESPACE USERS;

-- Enable auto-login for dev_user
GRANT UNLIMITED TABLESPACE TO dev_user; 